### PR TITLE
fix: base path

### PR DESCRIPTION
**Pull request by locene**
Fixes https://github.com/chenasraf/simple-scaffold/issues/44

### CODE REVIEW

**Comment by chenasraf** [comment]
Damn, can't believe it's this simple.
I will verify this tomorrow and if it works I will merge it and put up a new version after I verify/add more tests for this.

Thank you for the work! If this gets merged I will happily award you the bounty

**Comment by chenasraf** [comment]
The fix is verified. @locene, thank you very much for your work!

**Review by chenasraf — APPROVED** [review]

**Comment by chenasraf** [comment]
@locene Please claim the bounty on [the bounty page](https://app.bountysource.com/issues/117463371-base-path-of-templates-always-added-to-the-output-path) and I will make sure to approve it.

**Comment by locene** [comment]
Claimed, happy cooperation!

**Pull request merged**
