### PR TITLE
v1.0

### PR DESCRIPTION
**Pull request by chenasraf**
## General

- [x] Rewrite everything to work faster and more efficiently
- [x] Improve templating system with case helpers (camelCase, PascalCase, kebab-case, snake_case)
- [x] Added tests
- [x] Improve args parsing
- [x] Improve file resolution
- [x] Remove output from repository
- [x] Documentation - README
- [ ] Documentation - MIGRATING

## Fix before release
- [x] Maintain folder structure on output
- [x] Tests only working some of the time
- [ ] Clean up files and functions

### CODE REVIEW

**Comment by jonnysamps** [comment]
Hey there, thanks for the work. Anything I can do to push this PR forward?

**Comment by chenasraf** [comment]
Hi @jonnysamps,

I will try to make more time to get progress on this. Is there a specific feature you're waiting for? The current version is pretty usable. Maybe I can push up something specific if it would help.

**Comment by jonnysamps** [comment]
@chenasraf ya, it totally is. I'm looking for a way to silence the logging output (there is a lot) because I'm incorporating it into a CLI tool so I don't want all of the debugging output.

I figured out a way to temporarily overwrite console.log/info so I don't really need it but I appreciate the work you've done and I thought I'd offer to help :D

**Comment by chenasraf** [comment]
I'll do my best to add the quiet flag to the current version this week. Shouldn't be a lot of work. Glad to hear you're using the package :)

**Comment by chenasraf** [comment]
@jonnysamps version 0.7.3 should have the `--quiet` arg added, please let me know if it works well for you or something else needs to be done.

**Pull request merged**
